version: "3"

services:
  subscribeserver:
    build: .
    ports:
    - "8181:8181"
    depends_on:
      - db
    links:
      - "db"
    networks:
      - fullstack
    stop_grace_period: 30s
    stop_signal: SIGTERM
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=qwerty
      - DB_BASE=SubscribeService
      - SUB_SERVICE_SYNC_TIME=10

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: SubscribeService
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fullstack
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - fullstack
    depends_on:
      - db

networks:
  fullstack:
    driver: bridge